import Header from "../components/Header/Header";
import Wrapper from "../components/Wrapper/Wrapper";
import global from "../styles/global.css";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <>
    <Head>
        <title>
          lucas neves - desenvolvimento web, front-end, tecnologia e derivados.
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Wrapper>
        <Component {...pageProps} />
      </Wrapper>
    </>
  );
}

export default MyApp;
