import Head from "next/head";
import Header from "../components/Header/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>
          lucas neves - desenvolvimento web, front-end, tecnologia e derivados.
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2>Home</h2>
      </main>

      <footer></footer>
    </div>
  );
}
